
server:
  port: 8080

database:
  dbserver: "localhost" 
  dbport: "27017"
  dbname: "local"
  maxpoolsize : 100


application:
  useStubDB : false # false -> (Real Mongo DB instance) true -> (Stub DB with sample responses) 
  maxrecordperpage: 12 #Maximum record count per page in query results
